# Site
name: "The OpenFn Blog"
title: "The OpenFn Blog"
description: "We help the world's most promising social impact interventions achieve scale through automation, data integration, and interoperability. This is our story."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
# baseurl: ""
google_analytics: "UA-57118569-10"
disqus: "openfn"
mailchimp-list: "https://openfn.us11.list-manage.com/subscribe/post?u=ad898e5a4d5a9aab0bbd63aee&amp;id=bf982e5409"
include: ["_pages", "_pages/authors"]
permalink: /:title/

# Authors
authors:
  taylor:
    name: Taylor
    display_name: Taylor Downs
    gravatar: 56373287c62e094d0f4f367fd993ff79
    email: taylor@openfn.org
    web: https://www.openfn.org/leadership#Taylor
    twitter: https://twitter.com/taylordowns2000
    description: "Head of Product at OpenFn"
  aleksa:
    name: Aleksa
    display_name: Aleksa Krolls
    gravatar: b59257a59a25dfc3b3e3ba1b5184dbf4
    email: aleksa@openfn.org
    web: https://www.openfn.org/leadership#Aleksa
    twitter: https://twitter.com/aleksa_krolls
    description: "Head of Services at OpenFn"
  leilei:
    name: Lei Lei
    display_name: Lei Lei Tun
    gravatar: 94a4f7570b9b6a5f253e59668bd0943a
    email: leilei@openfn.org
    # web: https://docs.openfn.org/authors/leilei
    # twitter: https://twitter.com/aleksa_krolls
    description: "Communications Specialist at OpenFn"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
